### ISSUE TITLE
Reorder Documentation

### ISSUE THREAD

**Issue by chrisgaun** [kudobuilder/www#5]
The documentation is not in a standard order. 

**Current Order**
Examples
- Apache Kafka
- Apache Zookeeper
- MySQL with Backup
CLI Usage
Community
Concepts
Getting Started

**Suggested Order**
Getting Started
Concepts
Examples
- Apache Kafka
- Apache Zookeeper
- MySQL with Backup
CLI Usage
Community

**Comment by guenter** [comment]
Mostly fixed by kudobuilder/kudo#147. I have not yet figured out how to move the examples section (or any subtree) so that's still at the top.
